/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIMostPopularChoice.java
 *
 * Created on 21/06/2009, 17:25:15
 */

package gui;

import java.awt.event.ActionListener;

/**
 *
 * @author Guilherme
 */
public class GUIMostPopularChoice extends javax.swing.JFrame {

    /** Creates new form GUIMostPopularChoice */
    public GUIMostPopularChoice() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labelText = new javax.swing.JLabel();
        buttonOK = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        selectedUsersRadioButton = new javax.swing.JRadioButton();
        allNetworkRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuários mais populares");
        setResizable(false);

        labelText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelText.setText("Abrir visualização dos usuários mais populares");

        buttonOK.setText("OK");
        buttonOK.setActionCommand("buttonOKMostPopularUsersChoice");
        buttonOK.setName("buttonOKAddUser"); // NOI18N

        buttonCancel.setText("Cancelar");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonGroup1.add(selectedUsersRadioButton);
        selectedUsersRadioButton.setSelected(true);
        selectedUsersRadioButton.setText("Para usuários selecionados");

        buttonGroup1.add(allNetworkRadioButton);
        allNetworkRadioButton.setText("Para a rede toda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allNetworkRadioButton)
                    .addComponent(selectedUsersRadioButton)
                    .addComponent(labelText)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancel)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectedUsersRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allNetworkRadioButton)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOK)
                    .addComponent(buttonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMostPopularChoice().setVisible(true);
            }
        });
    }

    public void addMainWindowListener(ActionListener listener) {
		buttonOK.addActionListener(listener);
	}

    public boolean forSelectedUsersOnly()
    {
        return selectedUsersRadioButton.isSelected();
    }

    // Variables declaration - do not modify
    private javax.swing.JRadioButton allNetworkRadioButton;
    private javax.swing.JButton buttonCancel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel labelText;
    private javax.swing.JRadioButton selectedUsersRadioButton;
    // End of variables declaration

}
