package gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.List;

import gui.visualizations.TagCloudView;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import twitter4j.TwitterResponse;

public class GUITagCloud extends JFrame {
	
	private TagCloudView panel;
	

	public GUITagCloud(List<TwitterResponse> statusesList, boolean isGroup, String name) {
		super("DeepTwitter - Tag Cloud");
		initComponents();
		
		setVisible(true);
		setLocationRelativeTo(null);
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		
		panel = new TagCloudView(statusesList, isGroup, name);
		init();
		
	}

	private void init() {
		
		
		panel.setBackground(Color.WHITE);
		add(panel, BorderLayout.CENTER);
		setSize(700, 500);
		
		JPanel legendPanel = new JPanel();
		legendPanel.setLayout(new FlowLayout());
		legendPanel.setBackground(Color.WHITE);

		JPanel panelCategories = new JPanel();
		panelCategories.setBackground(new Color(TagCloudView.colorCategories));
		JLabel labelCategories = new JLabel("Categories");
		labelCategories.setForeground(Color.WHITE);
		labelCategories.setFont(new Font("Tahoma", Font.BOLD, 16));
		panelCategories.add(labelCategories);
		
		JPanel panelTrends = new JPanel();
		panelTrends.setBackground(new Color(TagCloudView.colorTrends));
		JLabel labelTrends = new JLabel("Popular Topics");
		labelTrends.setForeground(Color.WHITE);
		labelTrends.setFont(new Font("Tahoma", Font.BOLD, 16));
		panelTrends.add(labelTrends);
		
		JPanel panelCategoriesTrends = new JPanel();
		panelCategoriesTrends.setBackground(new Color(TagCloudView.colorBoth));
		JLabel labelCategoriesTrends = new JLabel("Categories and Popular Topics");
		labelCategoriesTrends.setForeground(Color.WHITE);
		labelCategoriesTrends.setFont(new Font("Tahoma", Font.BOLD, 16));
		panelCategoriesTrends.add(labelCategoriesTrends);
		
		legendPanel.add(panelCategories);
		legendPanel.add(panelTrends);
		legendPanel.add(panelCategoriesTrends);
		
		
		add(legendPanel, BorderLayout.SOUTH);
		
		setLocationRelativeTo(null);
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(new java.awt.BorderLayout());

		pack();
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 */
//	public static void main(String args[]) {
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new GUITagCloud().setVisible(true);
//			}
//		});
//
//	}
}
