package gui;

import java.awt.event.ActionListener;
import java.util.Date;

import javax.swing.JLabel;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import javax.swing.JToggleButton;
import javax.swing.JToolBar;

import controller.ControllerDeepTwitter;

/**
 *
 * @author rotta
 */
public class GUIMainWindow extends javax.swing.JFrame {    
    /** Creates new form GUIMainWindow */
    public GUIMainWindow(String windowName) {
        super(windowName);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        labelStatusBar = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        buttonNewDirectMessage = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        buttonPreviousUser = new javax.swing.JButton();
        txtCurrentUser = new javax.swing.JTextField();
        buttonNextUser = new javax.swing.JButton();
        buttonSearchUpdates = new javax.swing.JButton();
        buttonInbox = new javax.swing.JToggleButton();
        buttonOutbox = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        buttonCloseUpdates = new javax.swing.JButton();
        buttonTurnOnOff = new javax.swing.JToggleButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        buttonTimeline = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        mainToolBar = new javax.swing.JToolBar();
        buttonUpdate = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        buttonAddUser = new javax.swing.JButton();
        buttonNewGroup = new javax.swing.JButton();
        buttonClearSelection = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        buttonCategoryEditor = new javax.swing.JButton();
        buttonMostActive = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        buttonToolTipControl = new javax.swing.JToggleButton();
        buttonCenterUser = new javax.swing.JToggleButton();
        buttonHighQuality = new javax.swing.JToggleButton();
        buttonCurvedEdges = new javax.swing.JToggleButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        buttonShowStatusBar = new javax.swing.JToggleButton();
        buttonPlayPauseVisualization = new javax.swing.JToggleButton();
        buttonSettings = new javax.swing.JButton();
        buttonForces = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        labelAPILimit = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        buttonHelp = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("DeepTwitter"); // NOI18N

        labelStatusBar.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelStatusBar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelStatusBar.setText(" ");
        labelStatusBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        labelStatusBar.setName("labelStatusBar"); // NOI18N
        getContentPane().add(labelStatusBar, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setDividerSize(6);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setOneTouchExpandable(true);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1100, 600));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        buttonNewDirectMessage.setIcon(new javax.swing.ImageIcon(("img/mail_add.png"))); // NOI18N
        buttonNewDirectMessage.setToolTipText("Nova mensagem direta");
        buttonNewDirectMessage.setActionCommand("buttonNewDirectMessage");
        buttonNewDirectMessage.setFocusable(false);
        buttonNewDirectMessage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNewDirectMessage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonNewDirectMessage);
        jToolBar1.add(jSeparator2);

        buttonPreviousUser.setIcon(new javax.swing.ImageIcon(("img/backward.png"))); // NOI18N
        buttonPreviousUser.setToolTipText("Usuário anterior");
        buttonPreviousUser.setActionCommand("buttonPreviousUser");
        buttonPreviousUser.setEnabled(false);
        buttonPreviousUser.setFocusable(false);
        buttonPreviousUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPreviousUser.setMinimumSize(new java.awt.Dimension(31, 31));
        buttonPreviousUser.setName("buttonPreviousUser"); // NOI18N
        buttonPreviousUser.setPreferredSize(new java.awt.Dimension(31, 31));
        buttonPreviousUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonPreviousUser);

        txtCurrentUser.setBackground(new java.awt.Color(240, 240, 240));
        txtCurrentUser.setEditable(false);
        txtCurrentUser.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtCurrentUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCurrentUser.setText("username");
        txtCurrentUser.setAutoscrolls(false);
        txtCurrentUser.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 0, true));
        txtCurrentUser.setMargin(new java.awt.Insets(0, 0, 0, 0));
        txtCurrentUser.setMaximumSize(new java.awt.Dimension(120, 14));
        txtCurrentUser.setMinimumSize(new java.awt.Dimension(120, 14));
        txtCurrentUser.setPreferredSize(new java.awt.Dimension(60, 14));
        jToolBar1.add(txtCurrentUser);

        buttonNextUser.setIcon(new javax.swing.ImageIcon(("img/forward.png"))); // NOI18N
        buttonNextUser.setToolTipText("Próximo usuário");
        buttonNextUser.setActionCommand("buttonNextUser");
        buttonNextUser.setEnabled(false);
        buttonNextUser.setFocusable(false);
        buttonNextUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNextUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonNextUser);

        buttonSearchUpdates.setIcon(new javax.swing.ImageIcon(("img/search.png"))); // NOI18N
        buttonSearchUpdates.setToolTipText("Buscar");
        buttonSearchUpdates.setActionCommand("buttonSearchUpdates");
        buttonSearchUpdates.setFocusable(false);
        buttonSearchUpdates.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonSearchUpdates.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonSearchUpdates);

        buttonInbox.setIcon(new javax.swing.ImageIcon(("img/mail_inbox.png"))); // NOI18N
        buttonInbox.setSelected(true);
        buttonInbox.setToolTipText("Caixa de Entrada");
        buttonInbox.setActionCommand("buttonInbox");
        buttonInbox.setFocusable(false);
        buttonInbox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonInbox.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonInbox);

        buttonOutbox.setIcon(new javax.swing.ImageIcon(("img/mail_outbox.png"))); // NOI18N
        buttonOutbox.setToolTipText("Caixa de Saída");
        buttonOutbox.setActionCommand("buttonOutbox");
        buttonOutbox.setFocusable(false);
        buttonOutbox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonOutbox.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonOutbox);
        jToolBar1.add(jSeparator4);

        buttonCloseUpdates.setIcon(new javax.swing.ImageIcon(("img/remove.png"))); // NOI18N
        buttonCloseUpdates.setToolTipText("Fechar este usuário");
        buttonCloseUpdates.setActionCommand("buttonCloseUpdates");
        buttonCloseUpdates.setFocusable(false);
        buttonCloseUpdates.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCloseUpdates.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonCloseUpdates);

        buttonTurnOnOff.setIcon(new javax.swing.ImageIcon(("img/turn_on.png"))); // NOI18N
        buttonTurnOnOff.setSelected(true);
        buttonTurnOnOff.setToolTipText("Ligar/desligar atualizar automaticamente");
        buttonTurnOnOff.setActionCommand("buttonTurnOnOff");
        buttonTurnOnOff.setFocusable(false);
        buttonTurnOnOff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonTurnOnOff.setSelectedIcon(new javax.swing.ImageIcon(("img/turn_off.png"))); // NOI18N
        buttonTurnOnOff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonTurnOnOff);
        jToolBar1.add(jSeparator5);

        buttonTimeline.setIcon(new javax.swing.ImageIcon(("img/eye.png"))); // NOI18N
        buttonTimeline.setToolTipText("Visualização do timeline de atualizações");
        buttonTimeline.setActionCommand("buttonTimeline");
        buttonTimeline.setFocusable(false);
        buttonTimeline.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonTimeline.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(buttonTimeline);
        buttonTimeline.getAccessibleContext().setAccessibleDescription("Visualização do Timeline de Atualizações");

        jPanel2.add(jToolBar1, java.awt.BorderLayout.PAGE_START);
        jPanel2.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Atualizações", jPanel2);

        jSplitPane1.setLeftComponent(jTabbedPane1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        mainToolBar.setFloatable(false);
        mainToolBar.setRollover(true);

        buttonUpdate.setIcon(new javax.swing.ImageIcon(("img/comment_add.png"))); // NOI18N
        buttonUpdate.setToolTipText("Novo tweet");
        buttonUpdate.setActionCommand("buttonNewUpdate");
        buttonUpdate.setName("buttonNewUpdate"); // NOI18N
        mainToolBar.add(buttonUpdate);
        mainToolBar.add(jSeparator3);

        buttonAddUser.setIcon(new javax.swing.ImageIcon(("img/user_search.png"))); // NOI18N
        buttonAddUser.setToolTipText("Procurar por usuário do Twitter");
        buttonAddUser.setActionCommand("buttonAddUser");
        buttonAddUser.setName("buttonAddUser"); // NOI18N
        mainToolBar.add(buttonAddUser);

        buttonNewGroup.setIcon(new javax.swing.ImageIcon(("img/users_add.png"))); // NOI18N
        buttonNewGroup.setToolTipText("Novo grupo");
        buttonNewGroup.setActionCommand("buttonNewGroup");
        buttonNewGroup.setName("buttonNewGroup"); // NOI18N
        mainToolBar.add(buttonNewGroup);

        buttonClearSelection.setIcon(new javax.swing.ImageIcon(("img/eraser.png"))); // NOI18N
        buttonClearSelection.setToolTipText("Limpar seleção");
        buttonClearSelection.setActionCommand("buttonClearSelection");
        buttonClearSelection.setFocusable(false);
        buttonClearSelection.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonClearSelection.setName("buttonClearSelection"); // NOI18N
        buttonClearSelection.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(buttonClearSelection);
        mainToolBar.add(jSeparator6);

        buttonCategoryEditor.setIcon(new javax.swing.ImageIcon(("img/archive.png"))); // NOI18N
        buttonCategoryEditor.setToolTipText("Gerenciador de Categorias");
        buttonCategoryEditor.setActionCommand("buttonCategoryEditor");
        buttonCategoryEditor.setFocusable(false);
        buttonCategoryEditor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCategoryEditor.setName("buttonShowAll"); // NOI18N
        buttonCategoryEditor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(buttonCategoryEditor);

        buttonMostActive.setIcon(new javax.swing.ImageIcon(("img/popularuser.png"))); // NOI18N
        buttonMostActive.setToolTipText("Visualização dos usuários mais populares");
        buttonMostActive.setActionCommand("buttonMostActive");
        buttonMostActive.setFocusable(false);
        buttonMostActive.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonMostActive.setName("buttonShowAll"); // NOI18N
        buttonMostActive.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(buttonMostActive);
        mainToolBar.add(jSeparator7);

        buttonToolTipControl.setIcon(new javax.swing.ImageIcon(("img/user_info.png"))); // NOI18N
        buttonToolTipControl.setSelected(true);
        buttonToolTipControl.setToolTipText("Exibir tooltip com informações do usuário");
        buttonToolTipControl.setActionCommand("buttonToolTipControl");
        buttonToolTipControl.setFocusable(false);
        buttonToolTipControl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonToolTipControl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(buttonToolTipControl);

        buttonCenterUser.setIcon(new javax.swing.ImageIcon(("img/target.png"))); // NOI18N
        buttonCenterUser.setToolTipText("Centralizar usuário ao clicar");
        buttonCenterUser.setActionCommand("buttonCenterUser");
        buttonCenterUser.setFocusable(false);
        buttonCenterUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCenterUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(buttonCenterUser);

        buttonHighQuality.setIcon(new javax.swing.ImageIcon(("img/Q.png"))); // NOI18N
        buttonHighQuality.setSelected(true);
        buttonHighQuality.setToolTipText("Exibir gráficos com alta qualidade");
        buttonHighQuality.setActionCommand("buttonHighQuality");
        buttonHighQuality.setFocusable(false);
        buttonHighQuality.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonHighQuality.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(buttonHighQuality);

        buttonCurvedEdges.setIcon(new javax.swing.ImageIcon(("img/arrow.png"))); // NOI18N
        buttonCurvedEdges.setToolTipText("Arestas curvas");
        buttonCurvedEdges.setActionCommand("buttonCurvedEdges");
        buttonCurvedEdges.setFocusable(false);
        buttonCurvedEdges.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonCurvedEdges.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(buttonCurvedEdges);
        mainToolBar.add(jSeparator8);

        buttonShowStatusBar.setIcon(new javax.swing.ImageIcon(("img/S.png"))); // NOI18N
        buttonShowStatusBar.setSelected(true);
        buttonShowStatusBar.setToolTipText("Exibir barra de status");
        buttonShowStatusBar.setActionCommand("buttonShowStatusBar");
        buttonShowStatusBar.setFocusable(false);
        buttonShowStatusBar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonShowStatusBar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(buttonShowStatusBar);

        buttonPlayPauseVisualization.setIcon(new javax.swing.ImageIcon(("img/play.png"))); // NOI18N
        buttonPlayPauseVisualization.setSelected(true);
        buttonPlayPauseVisualization.setToolTipText("Play/Pause animar rede");
        buttonPlayPauseVisualization.setActionCommand("buttonPlayPauseVisualization");
        buttonPlayPauseVisualization.setFocusable(false);
        buttonPlayPauseVisualization.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPlayPauseVisualization.setSelectedIcon(new javax.swing.ImageIcon(("img/pause.png"))); // NOI18N
        buttonPlayPauseVisualization.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(buttonPlayPauseVisualization);

        buttonSettings.setIcon(new javax.swing.ImageIcon(("img/config.png"))); // NOI18N
        buttonSettings.setToolTipText("Configurações");
        buttonSettings.setActionCommand("buttonSettings");
        buttonSettings.setFocusable(false);
        buttonSettings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonSettings.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(buttonSettings);

        buttonForces.setIcon(new javax.swing.ImageIcon(("img/F.png"))); // NOI18N
        buttonForces.setToolTipText("Forças físicas da rede");
        buttonForces.setActionCommand("buttonForces");
        buttonForces.setFocusable(false);
        buttonForces.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonForces.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(buttonForces);
        mainToolBar.add(jSeparator9);

        labelAPILimit.setFont(new java.awt.Font("Tahoma", 0, 12));
        labelAPILimit.setText("API:");
        mainToolBar.add(labelAPILimit);
        mainToolBar.add(jSeparator10);

        buttonHelp.setIcon(new javax.swing.ImageIcon(("img/help.png"))); // NOI18N
        buttonHelp.setToolTipText("Manual do usuário");
        buttonHelp.setActionCommand("buttonHelp");
        buttonHelp.setFocusable(false);
        buttonHelp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonHelp.setName("buttonShowAll"); // NOI18N
        buttonHelp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(buttonHelp);

        buttonLogout.setIcon(new javax.swing.ImageIcon(("img/logout.png"))); // NOI18N
        buttonLogout.setToolTipText("Logout");
        buttonLogout.setActionCommand("buttonLogout");
        buttonLogout.setFocusable(false);
        buttonLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonLogout.setName("buttonShowAll"); // NOI18N
        buttonLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mainToolBar.add(buttonLogout);

        getContentPane().add(mainToolBar, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>                        

    public void addMainWindowListener(ActionListener listener) {
		buttonLogout.addActionListener(listener);
        buttonShowStatusBar.addActionListener(listener);
        buttonHelp.addActionListener(listener);
        buttonAddUser.addActionListener(listener);
        buttonNewGroup.addActionListener(listener);
        buttonUpdate.addActionListener(listener);
        buttonClearSelection.addActionListener(listener);

        buttonCloseUpdates.addActionListener(listener);
        buttonPreviousUser.addActionListener(listener);
        buttonNextUser.addActionListener(listener);
        buttonTurnOnOff.addActionListener(listener);
        buttonSettings.addActionListener(listener);
        buttonTimeline.addActionListener(listener);

        buttonHighQuality.addActionListener(listener);
        buttonCurvedEdges.addActionListener(listener);
        buttonToolTipControl.addActionListener(listener);
        buttonPlayPauseVisualization.addActionListener(listener);
        buttonCenterUser.addActionListener(listener);
        buttonMostActive.addActionListener(listener);
        buttonCategoryEditor.addActionListener(listener);
        buttonForces.addActionListener(listener);
	}

    public boolean isHighQuality() {
        return buttonHighQuality.isSelected();
    }

    public boolean isCurvedEdges() {
        return buttonCurvedEdges.isSelected();
    }

    public boolean isToolTipControlOn() {
        return buttonToolTipControl.isSelected();
    }

    public boolean isVisualizationRunning() {
        return buttonPlayPauseVisualization.isSelected();
    }

    public boolean isCenterUserOn() {
        return buttonCenterUser.isSelected();
    }

    public boolean isStatusBarVisible() {
        return buttonShowStatusBar.isSelected();
    }   

    public void setStatusBarVisible(boolean b)  {
        labelStatusBar.setVisible(b);
    }

    public JLabel getStatusBarLabel() {
        return labelStatusBar;
    }

    public JSplitPane getSplitPane() {
        return jSplitPane1;
    }

    public JTabbedPane getTabs() {
        return jTabbedPane1;
    }

    public JToolBar getMainToolBar() {
        return mainToolBar;
    }

    public void setPreviousUserEnabled(boolean b) {
        buttonPreviousUser.setEnabled(b);
    }

    public void setNextUserEnabled(boolean b) {
        buttonNextUser.setEnabled(b);
    }

    public void setCurrentUserName(String s) {
        txtCurrentUser.setText(s);
    }

    public void setCloseUserEnabled(boolean b) {
        buttonCloseUpdates.setEnabled(b);
    }
    
    public void setRateLimitStatus(int left, int total, Date resetDate) {
        labelAPILimit.setText("API: "+left+"/"+total);
        labelAPILimit.setToolTipText("Reset às "+resetDate.getHours()+":"+resetDate.getMinutes());
        
        ControllerDeepTwitter.liberaMemoria();        
    }

    public JToggleButton getButtonCurvedEdges(){
    	return buttonCurvedEdges;
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonAddUser;
    private javax.swing.JButton buttonCategoryEditor;
    private javax.swing.JToggleButton buttonCenterUser;
    private javax.swing.JButton buttonClearSelection;
    private javax.swing.JButton buttonCloseUpdates;
    private javax.swing.JToggleButton buttonCurvedEdges;
    private javax.swing.JButton buttonForces;
    private javax.swing.JButton buttonHelp;
    private javax.swing.JToggleButton buttonHighQuality;
    private javax.swing.JToggleButton buttonInbox;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonMostActive;
    private javax.swing.JButton buttonNewDirectMessage;
    private javax.swing.JButton buttonNewGroup;
    private javax.swing.JButton buttonNextUser;
    private javax.swing.JToggleButton buttonOutbox;
    private javax.swing.JToggleButton buttonPlayPauseVisualization;
    private javax.swing.JButton buttonPreviousUser;
    private javax.swing.JButton buttonSearchUpdates;
    private javax.swing.JButton buttonSettings;
    private javax.swing.JToggleButton buttonShowStatusBar;
    private javax.swing.JButton buttonTimeline;
    private javax.swing.JToggleButton buttonToolTipControl;
    private javax.swing.JToggleButton buttonTurnOnOff;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelAPILimit;
    private javax.swing.JLabel labelStatusBar;
    private javax.swing.JToolBar mainToolBar;
    private javax.swing.JTextField txtCurrentUser;
    // End of variables declaration                   

}
