/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUINewUpdate.java
 *
 * Created on 18/03/2009, 14:52:35
 */

package gui;

import java.awt.Color;
import java.awt.event.ActionListener;

import model.StatusesType;

/**
 *
 * @author Guilherme
 */
public class GUINewUpdate extends javax.swing.JFrame {
   
    /** Creates new form GUINewUpdate */
    public GUINewUpdate() {
        initComponents();       
    }

    public GUINewUpdate(String username, StatusesType st) {
    	initComponents();
    	if(st == StatusesType.DIRECT_MESSAGES)
    		updateArea.setText("D "+username+" ");
    	else if(st == StatusesType.REPLIES)
    		updateArea.setText("@"+username+" ");
    	else
    		throw new IllegalArgumentException("Este StatusesType não é válido.");
    }   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        buttonOK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelMaxChars = new javax.swing.JLabel();
        buttonCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        updateArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Update");
        setResizable(false);

        buttonOK.setText("Atualizar");
        buttonOK.setActionCommand("buttonUpdate");
        buttonOK.setEnabled(false);
        buttonOK.setName("buttonUpdate"); // NOI18N
        buttonOK.setNextFocusableComponent(updateArea);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18));
        jLabel2.setText("What are you doing?");

        labelMaxChars.setFont(new java.awt.Font("Georgia", 1, 18));
        labelMaxChars.setForeground(new java.awt.Color(153, 153, 153));
        labelMaxChars.setText("140");

        buttonCancel.setText("Cancelar");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        updateArea.setColumns(20);
        updateArea.setFont(new java.awt.Font("Arial", 0, 13));
        updateArea.setLineWrap(true);
        updateArea.setRows(5);
        updateArea.setTabSize(0);
        updateArea.setWrapStyleWord(true);
        updateArea.setNextFocusableComponent(buttonCancel);
        updateArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateAreaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                updateAreaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(updateArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                        .addComponent(labelMaxChars))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelMaxChars))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel)
                    .addComponent(buttonOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {                                             
        this.dispose();
    }                                            

    private void updateAreaKeyPressed(java.awt.event.KeyEvent evt) {                                      
        if(evt.getKeyCode()==9) {
            buttonCancel.requestFocusInWindow();
            return;
        }
        verifyConditions();
}                                     

    private void updateAreaKeyReleased(java.awt.event.KeyEvent evt) {                                       
        if(evt.getKeyCode()==9) {
            buttonCancel.requestFocusInWindow();
            return;
        }
        verifyConditions();
}                                      

    public void verifyConditions() {
        int textSize = updateArea.getText().length();
        //System.out.println("size: "+textSize);
        int remaining = 140-textSize;
        labelMaxChars.setText(String.valueOf(remaining));

        if(remaining<0) {
            buttonOK.setEnabled(false);
        }
        else if(remaining<10) {
            labelMaxChars.setForeground(Color.RED);
            buttonOK.setEnabled(true);
        }
        else if(remaining<20) {
            labelMaxChars.setForeground(Color.RED.darker().darker());
            buttonOK.setEnabled(true);
        }
        else if(remaining==140) {
        	buttonOK.setEnabled(false);
        }
        else {
            labelMaxChars.setForeground(new Color(153,153,153));
            buttonOK.setEnabled(true);
        }
    }

    public String getStatus() {
        return updateArea.getText();
    }

    public void addMainWindowListener(ActionListener listener) {
		buttonOK.addActionListener(listener);
	}

    // Variables declaration - do not modify
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMaxChars;
    private javax.swing.JTextArea updateArea;
    // End of variables declaration

}
