/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIMostActiveUsers.java
 *
 * Created on 09/06/2009, 02:18:57
 */

package gui;

import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author Guilherme
 */
public class GUIMostActiveUsers extends javax.swing.JFrame {

    /** Creates new form GUIMostActiveUsers */
    public GUIMostActiveUsers() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menuPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuários mais ativos");

        jSplitPane1.setDividerLocation(500);
        jSplitPane1.setDividerSize(6);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setContinuousLayout(true);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(800, 600));
        jSplitPane1.setOneTouchExpandable(true);

        menuPanel.setLayout(new java.awt.GridLayout(1, 2, 2, 1));
        jSplitPane1.setRightComponent(menuPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JSplitPane getSplitPane() {
        return jSplitPane1;
    }

    public JPanel getMenuPanel() {
        return menuPanel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables

}
